// src/view-angular/src/app/features/sign-in/sign-in-page.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Validators, FormBuilder, FormGroup } from '@angular/forms';

import { UserService } from '@domain/services/user';
import { UserModel } from '@domain/models/user';

@Component({
  selector: 'app-sign-in-page',
  templateUrl: './sign-in-page.component.html',
  styleUrls: ['./sign-in-page.component.scss']
})
export class SignInPageComponent {
  user: UserModel;

  constructor(private userSrv: UserService, private router: Router) {
    
  }




  navigateToTdeeCalculator() {
    this.router.navigate(['tdee']);
  }


  createUser() {
    this.user = this.userSrv.createUser({ id: '123', username: 'clark-kent' });
  }
}

<div class="sign-in-page">
  <h1>Sign in page</h1>

  <button (click)="navigateToTdeeCalculator()">Go to TDEE calculator</button>

  <div style="padding-top: 1rem;">
    <button (click)="createUser()">Create user</button>

    <h3>Our user:</h3>
    <p>
      <span>Username: {{ user?.state.username }}</span>
    </p>
    <div *ngIf="user">
      <input
        [ngModel]="user?.state.username"
        (input)="user?.updateUsername($event.target.value)" />
    </div>
  </div>
  
</div>

// src/view-vue/src/app/features/user/sign-in-page/sign-in-page.component.ts
import { Vue, Component, Prop } from 'vue-property-decorator';
import { UserModel } from '@domain/models/user';
import { UserService } from '@domain/services/user';
import { DI } from '@thenja/DI';


@Component({
  name: 'sign-in-page',
})
export default class SignInPageComponent extends Vue {
  public user: UserModel;
  public title!: string;

  @DI.Inject(UserService)
  private userSrv: UserService;

  constructor() {
    super();
    this.title = 'Hello!';
    this.user = this.userSrv.createUser({ id: '123', username: 'clark-kent' });
    this.user = new UserModel({ id: '123', username: 'clark-kent' });
  }
}
